var Five = 5;
var Ten = 10;
console.log("Test 1: Five is equal to 5?");
console.log(Five == 5);
console.log("Test 2: Ten is equal to 10?");
console.log(Ten == 10);
console.log("\nTest 3: 5 is not equal to 10");
console.log(Five != Ten);
console.log("\nTest 4: 10 is greater than 5");
console.log(Ten > Five);
console.log("\nTest 5: 5 is smaller than 10");
console.log(Five < Ten);
console.log("\nTest 6: 10 is smaller than 5");
console.log(Ten < Five);
console.log("\n Test 7: 5 is equal to 10");
console.log(Five == Ten);
console.log("\nTest 8: 10 is not equal 10");
console.log(Ten != Ten);
console.log("\nTest 9: 5 is greater than 10");
console.log(Five > Ten);
console.log("\nTest 10: 100 is smaller than 50");
console.log(100 < 50);
